In [ ]:
# importing necessary libraries
import pandas as pd
import numpy as np
!pip install kmodes
from kmodes.kmodes import KModes
import matplotlib.pyplot as plt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting kmodes
  Downloading kmodes-0.12.2-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from kmodes) (1.2.0)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.7/dist-packages (from kmodes) (1.21.6)
Requirement already satisfied: scipy>=0.13.3 in /usr/local/lib/python3.7/dist-packages (from kmodes) (1.7.3)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.7/dist-packages (from kmodes) (1.0.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.22.0->kmodes) (3.1.0)
Installing collected packages: kmodes
Successfully installed kmodes-0.12.2

In [ ]:
data = pd.read_csv('/content/kmodes.csv')
data.head()

  Person hair color eye color skin color
0     p1     blonde     amber       fair
1     p2   brunette      gray      brown
2     p3        red     green      brown
3     p4      black     hazel      brown
4     p5   brunette     amber       fair

In [ ]:
kmode = KModes(n_clusters=3, init = "random", n_init = 5, verbose=1)
clusters = kmode.fit_predict(data)
clusters

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 0, cost: 11.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 0, cost: 15.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 1, cost: 11.0
Run 3, iteration: 2/100, moves: 1, cost: 11.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 0, cost: 11.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 3, cost: 12.0
Run 5, iteration: 2/100, moves: 0, cost: 12.0
Best run was number 1

array([1, 2, 0, 2, 1, 2, 0, 0], dtype=uint16)

In [ ]:
data.insert(0, "Cluster", clusters, True)
data

   Cluster Person hair color eye color skin color
0        1     p1     blonde     amber       fair
1        2     p2   brunette      gray      brown
2        0     p3        red     green      brown
3        2     p4      black     hazel      brown
4        1     p5   brunette     amber       fair
5        2     p6      black      gray      brown
6        0     p7        red     green       fair
7        0     p8      black     hazel       fair