20BRS1092 - NETHRA SAI

LAB 3  LOGISTIC REGRESSION

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

In [ ]:
train_set= pd.read_csv('/content/wheat_train.csv')
train_set_x= train_set.drop(['ID','Type'],axis=1)
train_set_x.head()

,area,perimeter,compactness,kernelLength,kernelWidth,asymmetryCoefficient,kernelGrooveLength.
0,18.59,16.05,0.9066,6.037,3.860,6.001,5.877
1,11.18,12.72,0.8680,5.009,2.810,4.051,4.828
2,15.99,14.89,0.9064,5.363,3.582,3.336,5.144
3,15.38,14.90,0.8706,5.884,3.268,4.462,5.795
4,19.15,16.45,0.8890,6.245,3.815,3.084,6.185

In [ ]:
train_set_y=train_set['Type']
train_set_y.head()

0    2
1    3
2    2
3    2
4    2
Name: Type, dtype: int64

In [ ]:
test_set=pd.read_csv('/content/wheat_test.csv')
tst= test_set.drop(['ID'],axis=1)
tst.head()

,area,perimeter,compactness,kernelLength,kernelWidth,asymmetryCoefficient,kernelGrooveLength.
0,18.85,16.17,0.9056,6.152,3.806,2.843,6.200
1,11.34,12.87,0.8596,5.053,2.849,3.347,5.003
2,14.86,14.67,0.8676,5.678,3.258,2.129,5.351
3,12.67,13.32,0.8977,4.984,3.135,2.300,4.745
4,11.82,13.40,0.8274,5.314,2.777,4.471,5.178

In [ ]:
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
regress=linear_model.LogisticRegression()
regress.fit(train_set_x,train_set_y)
print ('Coefficients: ', regress.coef_)
print ('Intercept: ',regress.intercept_)

Coefficients:  [[ 0.57774845 -0.67027011  0.01016325  0.26422249  0.12557349 -0.61011968
  -1.45974192]
 [ 1.05214166  1.17690544 -0.04625141 -0.16013611 -0.07601463  0.21215758
   0.67456452]
 [-1.62989011 -0.50663533  0.03608816 -0.10408639 -0.04955885  0.39796211
   0.7851774 ]]
Intercept:  [ 11.11527197 -36.14555498  25.03028301]

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

In [ ]:
type_predicted=regress.predict(train_set_x)
print(type_predicted)

[2 3 1 2 2 3 2 2 3 3 3 2 1 3 1 1 3 2 1 2 1 1 3 2 1 3 2 1 1 2 1 1 2 3 3 2 3
 1 2 3 2 2 3 1 1 1 1 3 3 2 3 1 1 1 3 2 2 3 2 3 2 1 3 3 3 2 3 2 3 1 2 3 3 3
 2 2 2 2 1 2 3 1 2 2 3 1 2 1 3 2 3 1 1 3 1 1 3 3 2 1 2 3 3 3 2 3 3 1 3 3 1
 1 3 1 1 1 3 1 2 1 3 1 3 2 3 1 2 3 3 2 1 3 1 2 1 3 2 3 2 1]